
services:
  grafana:
    image: grafana/grafana:11.6.0
    container_name: scope-grafana
    ports:
      - "53000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admindevpwd
    restart: unless-stopped


volumes:
  grafana-storage:
