services:
  backend-nginx:
    image: nginx:1.26
    container_name: scope-backend-nginx
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"